Add ScheduleParser CLI
yurii-litvinov/ExamSchedule pull request #3
Opened 2024-03-17 14:58 UTC by Belgrak

2024-03-25 11:31 UTC, yurii-litvinov requested changes

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParser/ScheduleParser.cs
> +                + "&overwrite=true");
Тут тоже, кстати, используйте интерполяцию строк

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +    token = Console.ReadLine();
Не, ReadLine не стоит использовать, правильнее это дело через параметры или конфигурационный файл принимать

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +        Console.WriteLine("Введите абсолютный путь до файла индивидуального графика:");
Зачем абсолютный? :)

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +    token = Console.ReadLine();
И вообще я в последнее время склоняюсь к тому, чтобы вообще Яндекс.Диск не беспокоить, а качать .xlsx оттуда вручную и вручную же заливать. Давайте, может, так сделаем? Это реально удобнее, чем долбаться с Access Token и клиентскими секретами.

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +    var fileStream = new FileStream(pathToFile, FileMode.Open);
using

2024-03-25 11:31 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +    var result = await new ScheduleParser.ScheduleParser(fileStream).ParseToTable(token, pathToTable);
А ещё, наверное, хотелось бы команд в духе "Обновить даты и отсортировать существующую таблицу".

2024-04-01 08:39 UTC, Belgrak commented on ScheduleParserCLI/Program.cs
> +    var result = await new ScheduleParser.ScheduleParser(fileStream).ParseToTable(token, pathToTable);
Если не указать файл индивидуального графика, то таблица просто отсортируется.

2024-04-03 14:09 UTC, yurii-litvinov commented on ScheduleParserCLI/Program.cs
> +var pathToTable = args[0];
Если аргументы не переданы, тут упадёт с невнятным сообщением, а должно бы выводить подсказку по аргументам

2024-04-03 14:09 UTC, yurii-litvinov approved these changes

2024-04-03 14:09 UTC, merged